import { model, Schema } from "mongoose";
import { IMarketingCampaignSlot } from "../interface/marketing-campaign-slot.interface";

const MarketingCampaignSlotSchema = new Schema<IMarketingCampaignSlot>(
  {
    companyCode: { type: String, required: true, index: true },
    campaignId: { type: Schema.Types.ObjectId, ref: "MarketingCampaign", required: true, index: true },
    scheduledAt: { type: Date, required: true, index: true },
    prepareAt: { type: Date, required: true, index: true },
    verifyAt: { type: Date, required: true, index: true },
    platform: { type: String, enum: ["Facebook", "TikTok"], required: true, index: true },
    integrationId: { type: Schema.Types.ObjectId, ref: "SocialIntegration", index: true },
    tiktokPublishOptions: {
      caption: { type: String, maxlength: 2200 },
      privacyLevel: {
        type: String,
        enum: ["PUBLIC_TO_EVERYONE", "MUTUAL_FOLLOW_FRIENDS", "FOLLOWER_OF_CREATOR", "SELF_ONLY"],
      },
      allowComment: { type: Boolean },
      allowDuet: { type: Boolean },
      allowStitch: { type: Boolean },
      brandContentToggle: { type: Boolean },
      brandContent: { type: Boolean },
      brandOrganic: { type: Boolean },
      isAigc: { type: Boolean },
      videoDurationSeconds: { type: Number, min: 0 },
      consentAccepted: { type: Boolean },
      _id: false,
    },
    pillar: { type: String, default: "" },
    objective: { type: String, required: true },
    topicBrief: { type: String, required: true },
    funnelStage: { type: String, enum: ["TOFU", "MOFU", "BOFU"], default: "MOFU", index: true },
    mediaType: { type: String, enum: ["text", "image", "video", "human-video"], required: true },
    mediaSource: {
      type: String,
      enum: ["drive", "ai", "upload", "production_order", "none"],
      default: "drive",
      index: true,
    },
    status: {
      type: String,
      enum: ["planned", "queued", "generating", "researching", "writing", "scoring", "awaiting_assets", "generating_media", "verifying", "pending_approval", "ready_to_publish", "publishing", "published", "retrying", "needs_attention", "failed", "skipped", "cancelled"],
      default: "planned",
      index: true,
    },
    approvedBy: { type: String },
    approvedAt: { type: Date },
    attemptCount: { type: Number, default: 0, min: 0 },
    lockId: { type: String, index: true },
    lockedAt: { type: Date },
    lockExpiresAt: { type: Date, index: true },
    selectedCandidateId: { type: Schema.Types.ObjectId, ref: "MarketingCandidate" },
    marketingContentId: { type: Schema.Types.ObjectId, ref: "MarketingContent" },
    realImageDriveUrls: { type: [String], default: [] },
    realImageDirectUrls: { type: [String], default: [] },
    mediaIngestionFingerprint: { type: String },
    ingestedMedia: [{
      sourceUrl: { type: String, required: true },
      url: { type: String, required: true },
      uploadedAt: { type: Date, required: true },
      _id: false,
    }],
    visualAnalysis: {
      fingerprint: { type: String },
      sourceUrls: { type: [String], default: [] },
      summary: { type: String },
      subjects: { type: [String], default: [] },
      visibleText: { type: [String], default: [] },
      setting: { type: String },
      visualStyle: { type: String },
      mood: { type: String },
      factualDetails: { type: [String], default: [] },
      marketingAngles: { type: [String], default: [] },
      cautions: { type: [String], default: [] },
      model: { type: String },
      analyzedAt: { type: Date },
      cost: { type: Number, default: 0 },
      billedAt: { type: Date },
      _id: false,
    },
    researchAnalysis: {
      fingerprint: { type: String },
      context: { type: String },
      model: { type: String },
      researchedAt: { type: Date },
      cost: { type: Number, default: 0 },
      evidence: [{
        source: { type: String, enum: ["google", "facebook", "tiktok"], required: true },
        sourceUrl: { type: String, required: true },
        title: { type: String },
        text: { type: String, required: true },
        author: { type: String },
        publishedAt: { type: Date },
        collectedAt: { type: Date, required: true },
        metrics: {
          views: { type: Number },
          likes: { type: Number },
          comments: { type: Number },
          shares: { type: Number },
          _id: false,
        },
        _id: false,
      }],
      apifyRuns: [{
        source: { type: String, enum: ["google", "facebook", "tiktok"], required: true },
        actorId: { type: String, required: true },
        runId: { type: String },
        datasetId: { type: String },
        status: { type: String, enum: ["succeeded", "failed", "skipped"], required: true },
        itemCount: { type: Number, required: true },
        estimatedCostUsd: { type: Number, required: true },
        providerCostUsd: { type: Number, required: true },
        billingMode: { type: String, enum: ["shadow", "live"], required: true },
        executedAt: { type: Date, required: true },
        error: { type: String },
        _id: false,
      }],
      providerCostUsd: { type: Number, default: 0 },
      billingMode: { type: String, enum: ["shadow", "live"], default: "shadow" },
      billedAt: { type: Date },
      _id: false,
    },
    customBodyText: { type: String },
    publishIdempotencyKey: { type: String, required: true, unique: true },
    publishRequestedAt: { type: Date },
    publishedPostId: { type: String },
    publishedUrl: { type: String },
    lastError: {
      type: { type: String, enum: ["retryable", "validation", "authentication", "budget", "provider", "terminal"] },
      message: { type: String },
      occurredAt: { type: Date },
    },
    transitions: [{
      from: { type: String },
      to: { type: String, required: true },
      reason: { type: String },
      at: { type: Date, required: true, default: Date.now },
      _id: false,
    }],
  },
  { timestamps: true }
);

MarketingCampaignSlotSchema.index({ companyCode: 1, campaignId: 1, scheduledAt: 1 });
MarketingCampaignSlotSchema.index({ status: 1, prepareAt: 1, lockExpiresAt: 1 });
MarketingCampaignSlotSchema.index({ companyCode: 1, scheduledAt: 1 });
MarketingCampaignSlotSchema.index({ status: 1, verifyAt: 1, lockExpiresAt: 1 });
MarketingCampaignSlotSchema.index({ status: 1, scheduledAt: 1, lockExpiresAt: 1 });

export const MarketingCampaignSlotModel = model<IMarketingCampaignSlot>("MarketingCampaignSlot", MarketingCampaignSlotSchema);
